### ISSUE TITLE
Issues de GitHub

### ISSUE THREAD

**Issue by son0p** [brolin/ViZaJe#1]
No solo aparecen correos de la lista de unloquer, también aparecen los commits al repositorio de AQA ejemplo:

"Re: [unloquer/AQA] Problemas de con versión de librer","federico lopez <notifications@github.com>","unloquer/AQA <AQA@noreply.github.com>",16/10/2018 11:41, ,
"Re: [unloquer/AQA] Problemas de con versión de librer","federico lopez <notifications@github.com>","unloquer/AQA <AQA@noreply.github.com>",16/10/2018 11:41, ,
"Re: [unloquer/AQA] No tenemos una forma de diferencia","federico lopez <notifications@github.com>","unloquer/AQA <AQA@noreply.github.com>",16/10/2018 11:43, ,
"Re: [unloquer/AQA] No tenemos una forma de diferencia","federico lopez <notifications@github.com>","unloquer/AQA <AQA@noreply.github.com>",16/10/2018 11:43, ,

**Comment by brolin** [comment]
@son0p se pueden filtar los mensajes solo de la lista usando R así:

`require(tidyverse)
Mensajes2019 <- read_csv("./Data/2019/IndiceCorreos.csv", col_names=F)
colnames(Mensajes2019) <- c("subject","sender","date","hasattachment","truncatedcontent")
sinIssues <- Mensajes2019[!str_detect(Mensajes2019$subject,"Re: \\[unloquer/AQA\\].*"),] %>% as_tibble
`
